version: '3.8'

services:
  sqlserver:
    build:
      context: . 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/usr/config/init.sql
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: